=== IrenaKozlovskaya/SpringLibrary/SpringLibrary/src/main/resources/xml/booksXSD.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:element name="books">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="book" type="book" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:complexType name="book">
        <xsd:sequence>
            <xsd:element name="title" type="xsd:string"/>
            <xsd:element name="ISBN" type="xsd:string"/>
            <xsd:element name="authors" type="authors"/>
            <xsd:element name="genre" type="genre"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="authors">
        <xsd:sequence>
            <xsd:element name="firstAuthor" type="author"/>
            <xsd:element minOccurs="0" name="secondAuthor" type="author"/>
            <xsd:element minOccurs="0" name="thirdAuthor" type="author"/>
        </xsd:sequence>
    </xsd:complexType>


    <xsd:complexType name="author">
        <xsd:sequence>
            <xsd:element name="authorName" type="xsd:string"/>
        </xsd:sequence>
    </xsd:complexType>


    <xsd:complexType name="genre">
        <xsd:sequence>
            <xsd:element name="name" type="genreName"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:simpleType name="genreName">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="роман"/>
            <xsd:enumeration value="проза"/>
            <xsd:enumeration value="искусствоведение"/>
            <xsd:enumeration value="повесть"/>
            <xsd:enumeration value="наука"/>
        </xsd:restriction>
    </xsd:simpleType>

</xsd:schema>

=== IrenaKozlovskaya/SpringLibrary/SpringLibrary/src/main/resources/xml/books.xml
<?xml version="1.0" encoding="UTF-8"?>
<books xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="booksXSD.xsd">
    <book>
        <title>Убить пересмешника</title>
        <ISBN>213236565</ISBN>
        <authors>
            <firstAuthor>
                <authorName>Харпер Ли</authorName>
            </firstAuthor>
        </authors>
        <genre>
            <name>роман</name>
        </genre>
    </book>
    <book>
        <title>Пойди поставь сторожа</title>
        <ISBN>435435454</ISBN>
        <authors>
            <firstAuthor>
                <authorName>Харпер Ли</authorName>
            </firstAuthor>
        </authors>
        <genre>
            <name>проза</name>
        </genre>
    </book>
    <book>
        <title>Старик и море</title>
        <ISBN>21351654465</ISBN>
        <authors>
            <firstAuthor>
                <authorName>Хэмингуэй</authorName>
            </firstAuthor>
        </authors>
        <genre>
            <name>повесть</name>
        </genre>
    </book>
    <book>
        <title>Апокалипсис в искусстве</title>
        <ISBN>435458484</ISBN>
        <authors>
            <firstAuthor>
                <authorName>Софья Багдасарова</authorName>
            </firstAuthor>
        </authors>
        <genre>
            <name>искусствоведение</name>
        </genre>
    </book>
    <book>
        <title>По ком звонит колокол</title>
        <ISBN>35435435</ISBN>
        <authors>
            <firstAuthor>
                <authorName>Хэмингуэй</authorName>
            </firstAuthor>
        </authors>
        <genre>
            <name>роман</name>
        </genre>
    </book>
    <book>
        <title>Методы программирования</title>
        <ISBN>35436935</ISBN>
        <authors>
            <firstAuthor>
                <authorName>Блинов</authorName>
            </firstAuthor>
            <secondAuthor>
                <authorName>Романов</authorName>
            </secondAuthor>
        </authors>
        <genre>
            <name>наука</name>
        </genre>
    </book>
    <book>
        <title>Будет удалено</title>
        <ISBN>35436932</ISBN>
        <authors>
            <firstAuthor>
                <authorName>Блинов</authorName>
            </firstAuthor>
        </authors>
        <genre>
            <name>наука</name>
        </genre>
    </book>
</books>
